Add repo revew to tephi
SciTools/tephi pull request #164
Opened 2024-11-04 10:43 UTC by ESadek-MO

## 🚀 Pull Request
Closes #155 

- [ ] Adopt repo review, with all checks ignored for the time being
- [ ] Decide which standards should be maintained for tephi
- [ ] Implement changes so that tephi is in-line with these standards

2024-11-04 12:04 UTC, ESadek-MO commented
I'm happy for this to be merged in now, and then track ignores in #155

2024-11-14 15:06 UTC, trexfeathers requested changes

2024-11-14 15:06 UTC, trexfeathers commented on .pre-commit-config.yaml
> +        additional_dependencies: ["repo-review[cli]"]
```suggestion
        additional_dependencies: ["repo-review[cli]"]
        args: ["--show=errskip"]

```

Aligns with the [template](https://github.com/SciTools/.github/blob/main/templates/.pre-commit-config.yaml) (which itself is based on other SciTools repos).

2024-11-14 15:06 UTC, trexfeathers commented on pyproject.toml
> +]
Please can each of these include a URL to the documentation for this error, which is what we have done with other repos e.g.

- [Geovista](https://github.com/bjlittle/geovista/blob/36ea0db7005218897cf38f4a742c5757196e9314/pyproject.toml#L143-L151)
- [Iris-grib](https://github.com/SciTools/iris-grib/blob/d00965d4b411e12c4e6a166ee7903a2d1129c05e/pyproject.toml#L137-L149)

(I think I remember specific discussions about this, although I'm a bit hazy. That would suggest it's something we care about).

2024-11-20 12:26 UTC, ESadek-MO commented on pyproject.toml
> +  "RF001",  # Has Ruff config --
```suggestion
  # https://learn.scientific-python.org/development/guides/style/#PY005
  "PY005",  # Has tests folder --
  # https://learn.scientific-python.org/development/guides/style/#PP003
  "PP003",  # Does not list wheel as a build-dep --
  # https://learn.scientific-python.org/development/guides/style/#PP301
  "PP301",  # Has pytest in project --
  # https://learn.scientific-python.org/development/guides/style/#PP304
  "PP304",  # Sets the log level in pytest s
  # https://learn.scientific-python.org/development/guides/style/#PP305
  "PP305",  # Specifies xfail_strict
  # https://learn.scientific-python.org/development/guides/style/#PP306
  "PP306",  # Specifies strict config 
  # https://learn.scientific-python.org/development/guides/style/#PP307
  "PP307",  # Specifies strict markers
  # https://learn.scientific-python.org/development/guides/style/#PP309
  "PP309",  # Filter warnings specified
  # https://learn.scientific-python.org/development/guides/style/#GH212
  "GH212",  # Require GHA update grouping
  # https://learn.scientific-python.org/development/guides/style/#PC110
  "PC110",  # Uses black or ruff-format
  # https://learn.scientific-python.org/development/guides/style/#PC140
  "PC140",  # Uses a type checker
  # https://learn.scientific-python.org/development/guides/style/#PC160
  "PC160",  # Uses a spell checker
  # https://learn.scientific-python.org/development/guides/style/#PC170
  "PC170",  # Uses PyGrep hooks (only needed if rST present)
  # https://learn.scientific-python.org/development/guides/style/#PC180
  "PC180",  # Uses a markdown formatter
  # https://learn.scientific-python.org/development/guides/style/#PC190
  "PC190",  # Uses Ruff
  # https://learn.scientific-python.org/development/guides/style/#PC901
  "PC901",  # Custom pre-commit CI message
  # https://learn.scientific-python.org/development/guides/style/#MY100
  "MY100",  # Uses MyPy (pyproject config) --
  # https://learn.scientific-python.org/development/guides/style/#RF001
  "RF001",  # Has Ruff config --
```

2024-11-20 13:31 UTC, ESadek-MO commented on pyproject.toml
> +]
~~https://github.com/SciTools/tephi/pull/164/commits/db6695cc874649d90d20fd8e71c00cb17861675c~~ https://github.com/SciTools/tephi/pull/164/commits/23893dffb9dcb57a0616e87b2753b0ee98c03bfa

2024-11-20 14:10 UTC, stephenworsley approved these changes
Looks good!

2024-11-20 14:23 UTC, merged